#!/usr/bin/python3
'''
10819. 차이를 최대로
브루트포스
재귀이용해서 모든 경우의 수 고려
28776kb, 140ms
'''

import sys
max = float('-inf')
def go(cnt,pre_index,sum):
    global max
    if cnt == n:
        # 비교해주기
        if max < sum:
            max = sum
        return
    for i in range(n):
        if visited[i] == 0:
            origin_sum = sum
            sum += abs(a[pre_index]-a[i])
            visited[i] = 1
            go(cnt+1,i,sum)
            visited[i] = 0
            sum = origin_sum

n = int(input())
a = list(map(int,sys.stdin.readline().split()))

for i in range(n):
    visited = [0 for _ in range(n)]
    visited[i] = 1
    go(1,i,0)
print(max)
