#!/usr/bin/python3

"""
1149.rgb거리
123052kb, 120ms
"""
import sys
n = int(input())

dp = [[0 for _ in range(3)] for _ in range(n)]
matrix = []
for i in range(n):
    matrix.append(list(map(int,sys.stdin.readline().strip().split())))

for i in range(1,n):
    matrix[i][0] = min(matrix[i-1][1] + matrix[i][0], matrix[i-1][2] + matrix[i][0])
    matrix[i][1] = min(matrix[i-1][0] + matrix[i][1], matrix[i-1][2] + matrix[i][1])
    matrix[i][2] = min(matrix[i-1][0] + matrix[i][2], matrix[i-1][1] + matrix[i][2])

print(min(matrix[n-1]))
