#!/usr/bin/python3
"""
1182.부분수열의 합
28776kb 440ms
"""
import sys
from itertools import combinations
n,s = map(int,sys.stdin.readline().split())

l = list(map(int,sys.stdin.readline().split()))

cnt = 0
for i in range(1,n+1):
    for j in combinations(l,i):
        if sum(j) == s:
            cnt+=1

print(cnt)
