#!/usr/bin/python3

"""
1309.동물원

방법 1)
132368kb, 136ms
가로 한 칸에 주어질 수 있는 경우의 수 3가지 : 아무것도 안들어가거나, 오른쪽하나, 왼쪽하나

방법 2)
32628kb, 108ms
진짜로 하나하나 해봐서 점화식 구하기 -> 구하기 힘드니 방법1로 푸는게 나을듯

n = int(input())

dp = [0 for _ in range(n+1)]

dp[0] = 1
dp[1] = 3

for i in range(2,n+1):
        dp[i] = (dp[i-2]+ dp[i-1] * 2) % 9901

print(dp[n])
"""

n = int(input())

dp = [[0 for _ in range(3)] for _ in range(n)]

dp[0][0] = 1
dp[0][1] = 1
dp[0][2] = 1

for i in range(1,n):
    dp[i][0] = (dp[i-1][0] + dp[i-1][1] + dp[i-1][2]) % 9901
    dp[i][1] = (dp[i-1][0] + dp[i - 1][2]) % 9901
    dp[i][2] = (dp[i-1][0] + dp[i - 1][1]) % 9901
print(sum(dp[n-1]) % 9901)
