#!/usr/bin/python3

"""
14002. 가장 증가하는 긴 부분수열
123336kb, 140ms

현재값 기준으로 가장 길었던 거 합치기
야호 골드풀었다
"""
import sys

n = int(sys.stdin.readline())
a = list(map(int,sys.stdin.readline().split()))

# dp는 len 저장하는 리스트, dp2는 정답 문자열 저장하는 리스트 
dp = [0 for _ in range(n)]
dp2 = list(map(str,a))
for i in range(n):
    m = 1
    m2 = dp2[i]
    for j in range(i-1,-1,-1):
        if a[j] < a[i] and m < dp[j] + 1:
            m = dp[j] + 1
            m2 = dp2[j] + " " + dp2[i]
    dp2[i] = m2
    dp[i] = m

# dp중 가장 큰(긴) 값 가지고 있는 index 구하기
max = dp[0]
max_index = 0
for i in range(n):
    if max < dp[i]:
        max = dp[i]
        max_index = i
print(dp[max_index])
print(dp2[max_index])
