#!/usr/bin/python3
import sys

def change4():
    # 왼쪽으로 90도
    after_matrix = []
    n = len(matrix)
    m = len(matrix[0])
    #print(init_matrix)
    for i in range(m-1,-1,-1):  # 8
        l = []
        for j in range(n):
            l.append(matrix[j][i])
        after_matrix.append(l)
    return after_matrix

def check():
    total = 0
    for i in range(n):
        now = matrix[i][0]
        cnt = 1
        flag = 1
        visited = [0 for _ in range(n)]
        j = 1
        while j < n:
        # for j in range(1,n):
            if matrix[i][j] == now:
                cnt += 1
                j+=1
            elif matrix[i][j] == now + 1:
                # 올라가는 경사
                # print("cnt",i,j,cnt)
                if cnt < l:
                    # 경사로 설치못함
                    flag = 0
                    break
                else:
                    # 경사로 설치할 수 있음
                    # 설치한 위치 표시
                    for z in range(j - l, j):
                        visited[z] = 1
                    now = matrix[i][j]
                    cnt = 1
                j+=1
            elif matrix[i][j] == now - 1:
                # 내려가는 경사로
                if j + l - 1 >= n:
                    flag = 0
                    break
                flag2 = 1
                for z in range(j, j + l):
                    if matrix[i][j] != matrix[i][z]:
                        flag2 = 0
                        break
                if flag2 == 0:
                    flag = 0
                    break
                if j + l < n:
                    now = matrix[i][j+l-1]
                cnt = 0
                j = j + l
            else:
                # 2개 이상 차이
                flag = 0
                break
        if flag == 0:
            continue
        if flag == 1:
            total += 1
            # print(i)

    return total
n,l = map(int,sys.stdin.readline().split())

matrix = []
for i in range(n):
    matrix.append(list(map(int,sys.stdin.readline().split())))

rst = 0
rst += check()
#매트릭스 오른쪽으로 돌린다음에 검사
matrix = change4()
rst += check()
print(rst)
