#!/usr/bin/python3
import sys

"""
14499. 주사위돌리기
시뮬레이션
123052kb, 124ms

동서북남으로 돌렸을 때 각 면의 위치가 어디로 변하는지 확인하기
"""

l = [0,0,0,0,0,0,0]

n,m,x,y,k = map(int,sys.stdin.readline().split())

matrix = []
for i in range(n):
    matrix.append(list(map(int,sys.stdin.readline().split())))

# 동서북남 지도 이동
dx = [0,0,-1,1]
dy = [1,-1,0,0]

cmd = list(map(int,sys.stdin.readline().split()))

for i in cmd:
    nx = x + dx[i-1]
    ny = y + dy[i-1]

    if nx >= n or ny >= m or nx < 0 or ny < 0:
        # 범위 벗어남
        continue

    # 주사위 굴리기 경우
    if i == 1:
        #동쪽
        temp = l[1]
        l[1] = l[4]
        l[4] = l[6]
        l[6] = l[3]
        l[3] = temp
    elif i == 2:
        #서쪽
        temp = l[1]
        l[1] = l[3]
        l[3] = l[6]
        l[6] = l[4]
        l[4] = temp
    elif i == 3:
        #북쪽
        temp = l[1]
        l[1] = l[5]
        l[5] = l[6]
        l[6] = l[2]
        l[2] = temp
    elif i == 4:
        #남쪽
        temp = l[1]
        l[1] = l[2]
        l[2] = l[6]
        l[6] = l[5]
        l[5] = temp

    # 정상 범위
    if matrix[nx][ny] == 0:
        # 이동한 칸에 쓰여있는 수가 0이면
        matrix[nx][ny] = l[6]
    else:
        l[6] = matrix[nx][ny]
        matrix[nx][ny] = 0
    print(l[1])
    x = nx
    y = ny
