#!/usr/bin/python3
"""
15990. 123더하기5
시간초과 다시풀어보기...ㅠㅠ
"""
import sys
t = int(sys.stdin.readline())

# 각 값 중 1,2,3으로 시작하는 수를 구하기 위한 이차원 배열
dp2 = [[0 for _ in range(3)] for _ in range(100001)]

# range가 1,2,3이 아니라 0,1,2로 해놨으니까 -1해서 할당
dp2[1][0] = 1
dp2[2][1] = 1
dp2[3][0] = 1
dp2[3][1] = 1
dp2[3][2] = 1

for z in range(4,100001):
    dp2[z][0] = dp2[z-1][1]+dp2[z-1][2]
    dp2[z][1] = dp2[z-2][0]+dp2[z-2][2]
    dp2[z][2] = dp2[z-3][0]+dp2[z-3][1]

for i in range(t):
    n = int(sys.stdin.readline())
    print(sum(dp2[n]) % 1000000009)
