#!/usr/bin/python3
"""
123504,348
시뮬레이션
"""
import sys

n,k = map(int,sys.stdin.readline().split())

a = list(map(int,sys.stdin.readline().split()))

# 로봇이 현재 칸에 있는지 없는지 확인하기
check = [False for _ in range(2*n)]
total = 0
ans = 0
while True:
    ans  += 1
    a = a[-1:] + a[:-1]
    # 1. check 한칸씩 밀어주기
    for j in range(n-1,0,-1):
        check[j] = check[j-1]
    check[0] = False

    #print(check)
    if check[n-1]:
        check[n-1] = False

    # 2. 로봇 이동시키기
    for i in range(n-2,-1,-1):
        if check[i]:
            if check[i+1] == False and a[i+1] >= 1:
                check[i+1] = True
                check[i] = False
                a[i+1] -= 1
                if a[i+1] == 0:
                    total += 1

    if check[n-1]:
        check[n-1] = False

    #3. 올리는 칸에 내구도가 1 이상이면 올리고 내구도 -1 해주기
    if a[0] >= 1:
        check[0] = True
        a[0] -= 1
        if a[0] == 0:
            total += 1
    # 4. total 이 k개 이상이면 과정 종료
    if total >= k:
        break
print(ans)
