#!/usr/bin/python3

def solution(stones, k):
    answer = 0
    """
    이진탐색
    건널 수 있는 사람의 수 최대: stones의 최대값
    건널 수 있는 사람의 수 최소: 1명
    """
    left = 1
    right = max(stones)

    while left <= right:
        blankCount = 0

        mid = (left + right) // 2

        for i in stones:
            #연속되는 0의 수 구하기
            if i - mid <= 0:
                blankCount += 1
            else:
                blankCount = 0

            if blankCount == k:
                break

        if blankCount < k:
            left = mid + 1
            #여기서 왜 answer이 mid+1해준값인지 모르겠음 answer=mid가 맞지 않나....
            #만약에 mid + 1한 left값과 기존의 right값으로 이진탐색을 또 했을 때 blankCount==k가 되면 조건을 만족하지 않아서 정답이 되지 못하는게 아닐까.... . . . .. 
            answer = left
        else:
            right = mid - 1
    return answer
print(solution([2, 4, 5, 3, 2, 1, 4, 2, 5, 1],3))
